import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import StoreInitializer from "@/store/store-initializer";
import { useAuth } from "@/hooks/use-auth";
import { unstable_noStore as noStore } from "next/cache";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { fetchUser } = useAuth();
  const user = await fetchUser();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} border-2 antialiased flex justify-center min-h-screen max-h-screen min-w-sm max-w-md mx-auto`}
      >
        <StoreInitializer auth={user} />
        {children}
      </body>
    </html>
  );
}
